### ISSUE TITLE
`search_all_data_assets` not working as expected

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-codeocean-api#33]
**Describe the bug**
I'm trying to use `search_all_data_assets` to find all of the assets with a certain name prefix. This is leading to a bug.

**To Reproduce**
```python
for result in co_client.search_all_data_assets(query="name:SmartSPIM"):
    print(result)
```

yields

```
Traceback (most recent call last):
  File "/home/david.feng/projects/aind-data-migration-scripts/scripts/2023-03-13/update_asset_permissions.py", line 8, in <module>
    for result in co_client.search_all_data_assets(query="name:SmartSPIM"):
  File "/home/david.feng/miniconda3/envs/wrangle/lib/python3.10/site-packages/requests/models.py", line 828, in generate
    chunk = self.raw.read(chunk_size)
AttributeError: 'NoneType' object has no attribute 'read'
```

**Expected behavior**
This should iterate through the results and print them. This search works with the `co_client.search_data_assets` method, so I would expect to be able to copy-paste it to `search_all_data_assets`.

**Comment by dyf** [comment]
Not a bug.  `search_all_data_assets` just doesn't behave the way I expected.
